### PR TITLE
Bug 1111838

### PR DESCRIPTION
**Pull request by mmendieta**
Added a circular border around the Interest Pie graph which is zoom
in/out scalable.

classes changed:
interest-dashboard\data\css\devmenu\styles.css
interest-dashboard\data\about-you.html

### CODE REVIEW

**Comment by mmendieta** [comment]
Alright I'll take a look at it thank you

**Comment by emtwo** [comment]
@mmendieta the circular border work looks great! Feel free to move the code into a separate pull request with the two comments above addressed if you'd like to get it merged before finishing with the `Refresh` changes.

**Comment by mmendieta** [comment]
@emtwo I reverted the lines of code from Bug 1111821 so you can process this pull request independently.

Thank you again.

**Comment by emtwo** [comment]
@mmendieta Thanks. Once you've addressed the remaining two comments in this commit: https://github.com/mmendieta/interest-dashboard/commit/45543cd7c9b57ad4d0ac6fde5aa969c716a7dc78 we'll be ready to merge :)

**Comment by emtwo** [comment]
I squashed your commits into another pull request here: https://github.com/mozilla/interest-dashboard/pull/44 and will merge that one.

**Pull request closed without merging**
